### ISSUE TITLE
celery cam does not work

### ISSUE THREAD

**Issue by stefanfoulis** [aldryn/aldryn-celery#6]
error is something about app loading

**Comment by Chive** [comment]
```python
-> evcam: Taking snapshots with djcelery.snapshot.Camera (every 10.0 secs.)
Traceback (most recent call last):
  File "/virtualenv/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/virtualenv/lib/python3.5/site-packages/celery/__main__.py", line 30, in main
    main()
  File "/virtualenv/lib/python3.5/site-packages/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/virtualenv/lib/python3.5/site-packages/celery/bin/celery.py", line 793, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/virtualenv/lib/python3.5/site-packages/celery/bin/base.py", line 311, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/virtualenv/lib/python3.5/site-packages/celery/bin/celery.py", line 785, in handle_argv
    return self.execute(command, argv)
  File "/virtualenv/lib/python3.5/site-packages/celery/bin/celery.py", line 717, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/virtualenv/lib/python3.5/site-packages/celery/bin/base.py", line 315, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/virtualenv/lib/python3.5/site-packages/celery/bin/base.py", line 377, in handle_argv
    return self(*args, **options)
  File "/virtualenv/lib/python3.5/site-packages/celery/bin/base.py", line 274, in __call__
    ret = self.run(*args, **kwargs)
  File "/virtualenv/lib/python3.5/site-packages/celery/bin/events.py", line 86, in run
    detach=detach)
  File "/virtualenv/lib/python3.5/site-packages/celery/bin/events.py", line 113, in run_evcam
    return cam()
  File "/virtualenv/lib/python3.5/site-packages/celery/events/snapshot.py", line 103, in evcam
    maxrate=maxrate, timer=timer)
  File "/virtualenv/lib/python3.5/site-packages/celery/utils/imports.py", line 53, in instantiate
    return symbol_by_name(name)(*args, **kwargs)
  File "/virtualenv/lib/python3.5/site-packages/kombu/utils/__init__.py", line 96, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/virtualenv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/virtualenv/lib/python3.5/site-packages/djcelery/snapshot.py", line 15, in <module>
    from .models import WorkerState, TaskState
  File "/virtualenv/lib/python3.5/site-packages/djcelery/models.py", line 30, in <module>
    class TaskMeta(models.Model):
  File "/virtualenv/lib/python3.5/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/virtualenv/lib/python3.5/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/virtualenv/lib/python3.5/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by viktor-yunenko** [comment]
Is this really fixed? I'm facing the same error on django 2.2 and python 3.6 after following the divio celery configuration guide.

**Comment by viktor-yunenko** [comment]
Looks like on every divio project that I see people simple comment out the celerycam container.

**Comment by viktor-yunenko** [comment]
@vThaian , looks like the commit that was supposed to fix it was reverted later (https://github.com/divio/aldryn-celery/commit/2d62c27d82f1345bef31fd69a47e72348141e7f5), are you sure this ticket should be closed then?

**Comment by vladox** [comment]
@victor-yunenko @bplociennik still happening

**Comment by viktor-yunenko** [comment]
Hi @kinkerl, perhaps you know to whom we can assign this ticket?

cc @macolo
